"""init

Revision ID: 20beca6f4878
Revises: 
Create Date: 2025-12-07 21:09:09.013648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20beca6f4878'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cuidador',
    sa.Column('cedula', sa.String(), nullable=False),
    sa.Column('primernombre', sa.String(), nullable=False),
    sa.Column('segundonombre', sa.String(), nullable=True),
    sa.Column('primerapellido', sa.String(), nullable=False),
    sa.Column('segundoapellido', sa.String(), nullable=True),
    sa.Column('telefono', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('cedula')
    )
    op.create_index(op.f('ix_cuidador_cedula'), 'cuidador', ['cedula'], unique=False)
    op.create_table('medicamento',
    sa.Column('idmedicamento', sa.Integer(), nullable=False),
    sa.Column('nombremedicamento', sa.String(length=100), nullable=False),
    sa.Column('observaciones', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('idmedicamento')
    )
    op.create_index(op.f('ix_medicamento_idmedicamento'), 'medicamento', ['idmedicamento'], unique=False)
    op.create_table('paciente',
    sa.Column('cedula', sa.String(), nullable=False),
    sa.Column('primernombre', sa.String(), nullable=False),
    sa.Column('segundonombre', sa.String(), nullable=True),
    sa.Column('primerapellido', sa.String(), nullable=False),
    sa.Column('segundoapellido', sa.String(), nullable=True),
    sa.Column('telefono', sa.String(), nullable=False),
    sa.Column('fechanacimiento', sa.Date(), nullable=True),
    sa.CheckConstraint('fechanacimiento  < CURRENT_DATE', name='check_fecha_nacimiento'),
    sa.PrimaryKeyConstraint('cedula')
    )
    op.create_index(op.f('ix_paciente_cedula'), 'paciente', ['cedula'], unique=False)
    op.create_table('cuidador_paciente',
    sa.Column('cedulapaciente', sa.String(), nullable=False),
    sa.Column('cedulacuidador', sa.String(), nullable=False),
    sa.Column('fechaasignacion', sa.Date(), nullable=True),
    sa.Column('relacion', sa.String(), nullable=True),
    sa.CheckConstraint('fechaasignacion < CURRENT_DATE', name='check_fecha'),
    sa.ForeignKeyConstraint(['cedulacuidador'], ['cuidador.cedula'], ),
    sa.ForeignKeyConstraint(['cedulapaciente'], ['paciente.cedula'], ),
    sa.PrimaryKeyConstraint('cedulapaciente', 'cedulacuidador')
    )
    op.create_table('tratamiento',
    sa.Column('idtratamiento', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cedulapaciente', sa.String(), nullable=False),
    sa.Column('nombretratamiento', sa.String(), nullable=False),
    sa.Column('especialidad', sa.String(), nullable=False),
    sa.Column('fechainicio', sa.Date(), nullable=True),
    sa.Column('fechafin', sa.Date(), nullable=True),
    sa.CheckConstraint('fechafin > fechainicio AND fechafin <= CURRENT_DATE', name='check_fecha_fin'),
    sa.CheckConstraint('fechainicio < CURRENT_DATE', name='check_fecha_inicio'),
    sa.ForeignKeyConstraint(['cedulapaciente'], ['paciente.cedula'], ),
    sa.PrimaryKeyConstraint('idtratamiento')
    )
    op.create_index(op.f('ix_tratamiento_idtratamiento'), 'tratamiento', ['idtratamiento'], unique=False)
    op.create_table('recordatorio',
    sa.Column('idrecordatorio', sa.Integer(), nullable=False),
    sa.Column('idmedicamento', sa.Integer(), nullable=True),
    sa.Column('idtratamiento', sa.Integer(), nullable=True),
    sa.Column('estadoenvio', sa.Enum('Pendiente', 'Enviado', 'Error', name='estadoenvioenum'), nullable=False),
    sa.Column('respuestapaciente', sa.Enum('Confirmado', 'SinRespuesta', name='respuestapacienteenum'), nullable=False),
    sa.Column('fechaenviorecordatorio', sa.TIMESTAMP(), nullable=False),
    sa.Column('fecharespuesta', sa.TIMESTAMP(), nullable=True),
    sa.Column('notas', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['idmedicamento'], ['medicamento.idmedicamento'], ),
    sa.ForeignKeyConstraint(['idtratamiento'], ['tratamiento.idtratamiento'], ),
    sa.PrimaryKeyConstraint('idrecordatorio')
    )
    op.create_index(op.f('ix_recordatorio_idrecordatorio'), 'recordatorio', ['idrecordatorio'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recordatorio_idrecordatorio'), table_name='recordatorio')
    op.drop_table('recordatorio')
    op.drop_index(op.f('ix_tratamiento_idtratamiento'), table_name='tratamiento')
    op.drop_table('tratamiento')
    op.drop_table('cuidador_paciente')
    op.drop_index(op.f('ix_paciente_cedula'), table_name='paciente')
    op.drop_table('paciente')
    op.drop_index(op.f('ix_medicamento_idmedicamento'), table_name='medicamento')
    op.drop_table('medicamento')
    op.drop_index(op.f('ix_cuidador_cedula'), table_name='cuidador')
    op.drop_table('cuidador')
    # ### end Alembic commands ###
