"""cambio en patient

Revision ID: 458cc8ec8087
Revises: 20beca6f4878
Create Date: 2025-12-07 21:24:13.766633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '458cc8ec8087'
down_revision: Union[str, Sequence[str], None] = '20beca6f4878'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'paciente', ['telefono'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'paciente', type_='unique')
    # ### end Alembic commands ###
